# Generated by Django 3.1.6 on 2021-02-08 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('d_instruction', models.TextField()),
                ('d_opt', models.CharField(choices=[('InDh', 'Inside Dhaka (ID: 241)'), ('DhSub', 'Dhaka Sub (ID: 242)'), ('OutDh', 'Outside Dhaka HD (ID: 243)')], default='Please select', max_length=30)),
                ('service_charge', models.IntegerField(default=55)),
                ('d_area', models.CharField(max_length=30)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
