# Generated by Django 3.1.6 on 2021-02-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0003_auto_20210213_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='contact_no',
            field=models.IntegerField(max_length=11),
        ),
    ]
