# Generated by Django 3.1.6 on 2021-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0004_auto_20210213_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='contact_no',
            field=models.CharField(max_length=11),
        ),
    ]
