# Generated by Django 3.1.6 on 2021-02-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0005_auto_20210213_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_info',
            name='service_charge',
        ),
        migrations.CreateModel(
            name='Order_info_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge', models.IntegerField(default=55)),
                ('delivery_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersite.order_info')),
            ],
        ),
    ]
