# Generated by Django 3.1.6 on 2021-02-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0006_auto_20210222_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_info_delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_option', models.CharField(choices=[('InDh', 'Inside Dhaka (ID: 241)'), ('DhSub', 'Dhaka Sub (ID: 242)'), ('OutDh', 'Outside Dhaka HD (ID: 243)')], default='Please select', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='order_info',
            name='service_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersite.order_info_price'),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordersite.order_info_delivery'),
        ),
        migrations.AlterField(
            model_name='order_info_price',
            name='delivery_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersite.order_info_delivery'),
        ),
    ]
