# Generated by Django 3.1.6 on 2021-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0007_auto_20210222_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info_delivery',
            name='delivery_option',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_info_price',
            name='service_charge',
            field=models.CharField(max_length=5),
        ),
    ]
