# Generated by Django 3.1.6 on 2021-02-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regprofile',
            name='name_user',
            field=models.CharField(default='Your Name', max_length=100),
        ),
    ]
