# Generated by Django 3.1.6 on 2021-02-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationUser', '0002_regprofile_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regprofile',
            name='name_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
