# Generated by Django 3.1.6 on 2021-02-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationUser', '0003_auto_20210209_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regprofile',
            old_name='name_user',
            new_name='your_name',
        ),
    ]
