# Generated by Django 3.1.6 on 2021-03-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationUser', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='regprofile',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('bKash', 'bKash')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='regprofile',
            name='way_of_payment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
