# Generated by Django 3.1.6 on 2021-03-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_info_delivery',
            new_name='Order_delivery',
        ),
        migrations.RenameModel(
            old_name='Order_info_price',
            new_name='Order_price',
        ),
    ]
