# Generated by Django 3.1.6 on 2021-03-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210301_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Accessories', 'Accessories')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
