# Generated by Django 3.1.6 on 2021-03-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210302_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merchant_payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='way_of_payment',
        ),
    ]
