# Generated by Django 3.1.6 on 2021-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210307_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_charge',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default='To be assigned', max_length=15),
        ),
        migrations.DeleteModel(
            name='Order_price',
        ),
    ]
