# Generated by Django 3.1.6 on 2021-03-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210307_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.AddField(
            model_name='order',
            name='product_weight',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Order_delivery',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.all_area'),
        ),
    ]
