# Generated by Django 3.1.6 on 2021-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210317_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
    ]
