# Generated by Django 3.1.6 on 2021-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210323_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_from_customer',
            field=models.IntegerField(default=0),
        ),
    ]
