# Generated by Django 3.1.6 on 2021-03-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210323_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product_category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Returned', 'Returned'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
