# Generated by Django 3.1.6 on 2021-03-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210324_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_received',
            new_name='total_received_or_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
