# Generated by Django 3.1.6 on 2021-03-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210324_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to_deliveryman',
            field=models.CharField(default='', max_length=20),
        ),
    ]
